// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public final class HeatingServiceImpl {
  private HeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heating_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heating_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rheating.proto\022\007heating\"\035\n\014PowerRequest" +
      "\022\r\n\005state\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005stat" +
      "e\030\001 \001(\010\"\"\n\022TemperatureRequest\022\014\n\004temp\030\001 " +
      "\001(\005\"#\n\023TemperatureResponse\022\014\n\004temp\030\001 \001(\005" +
      "2\244\001\n\016HeatingService\022>\n\013changePower\022\025.hea" +
      "ting.PowerRequest\032\026.heating.PowerRespons" +
      "e\"\000\022R\n\021changeTemperature\022\033.heating.Tempe" +
      "ratureRequest\032\034.heating.TemperatureRespo" +
      "nse\"\0000\001B\037\n\007heatingB\022HeatingServiceImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heating_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heating_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_heating_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heating_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_heating_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_heating_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_TemperatureRequest_descriptor,
        new java.lang.String[] { "Temp", });
    internal_static_heating_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_heating_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heating_TemperatureResponse_descriptor,
        new java.lang.String[] { "Temp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
