// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heating.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
