// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heating.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();
}
