// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heating.proto

package heating;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heating.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();
}
