// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fax.proto

package fax;

public interface FaxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Fax.FaxResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
