// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fax.proto

package fax;

public final class FaxServiceImpl {
  private FaxServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fax_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fax_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fax_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fax_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fax_FaxRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fax_FaxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fax_FaxResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fax_FaxResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfax.proto\022\003Fax\"\035\n\014PowerRequest\022\r\n\005stat" +
      "e\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005state\030\001 \001(\010\"" +
      "\032\n\nFaxRequest\022\014\n\004text\030\001 \001(\t\"\033\n\013FaxRespon" +
      "se\022\014\n\004text\030\001 \001(\t2x\n\nFaxService\0226\n\013switch" +
      "Power\022\021.Fax.PowerRequest\032\022.Fax.PowerResp" +
      "onse\"\000\0222\n\007sendFax\022\017.Fax.FaxRequest\032\020.Fax" +
      ".FaxResponse\"\000(\0010\001B\027\n\003faxB\016FaxServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Fax_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Fax_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fax_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_Fax_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Fax_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fax_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_Fax_FaxRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Fax_FaxRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fax_FaxRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_Fax_FaxResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Fax_FaxResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fax_FaxResponse_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
