// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fax.proto

package fax;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Fax.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool state = 1;</code>
   */
  boolean getState();
}
