// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface BrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.BrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bright = 1;</code>
   */
  int getBright();
}
