// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public final class LightServiceImpl {
  private LightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_BrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_BrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_BrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_BrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013light.proto\022\005light\"\035\n\014PowerRequest\022\r\n\005" +
      "state\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005state\030\001 " +
      "\001(\010\"#\n\021BrightnessRequest\022\016\n\006bright\030\001 \001(\005" +
      "\"$\n\022BrightnessResponse\022\016\n\006bright\030\001 \001(\0052\224" +
      "\001\n\014LightService\022:\n\013changePower\022\023.light.P" +
      "owerRequest\032\024.light.PowerResponse\"\000\022H\n\rs" +
      "etBrightness\022\030.light.BrightnessRequest\032\031" +
      ".light.BrightnessResponse\"\000(\001B\033\n\005lightB\020" +
      "LightServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_light_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_light_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_PowerRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_light_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_light_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_PowerResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_light_BrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_light_BrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_BrightnessRequest_descriptor,
        new java.lang.String[] { "Bright", });
    internal_static_light_BrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_light_BrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_BrightnessResponse_descriptor,
        new java.lang.String[] { "Bright", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
